name: Node.js CI

on:
  push:
    branches: [test]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install npm dependencies
        run: yarn install --frozen-lockfile

      - name: Run linting
        run: yarn lint

      - name: Run tests with jest
        run: yarn test

      - name: Run coverage test
        run: yarn test:ci

      - name: Build App
        run: yarn build

      # - name: Test cypress
      #   run: yarn test:e2e

      # - name: Cypress.io
      #   uses: cypress-io/github-action@v3
      #   with:
      #     start: yarn start
      #     wait-on: "http://localhost:3000"
